// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: relay-proxy.proto

package relayproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RelayProxy_RegisterValidator_FullMethodName = "/RelayProxy/RegisterValidator"
	RelayProxy_GetHeader_FullMethodName         = "/RelayProxy/GetHeader"
	RelayProxy_GetPayload_FullMethodName        = "/RelayProxy/GetPayload"
	RelayProxy_StreamHeader_FullMethodName      = "/RelayProxy/StreamHeader"
)

// RelayProxyClient is the client API for RelayProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayProxyClient interface {
	RegisterValidator(ctx context.Context, in *RegisterValidatorRequest, opts ...grpc.CallOption) (*RegisterValidatorResponse, error)
	GetHeader(ctx context.Context, in *GetHeaderRequest, opts ...grpc.CallOption) (*GetHeaderResponse, error)
	GetPayload(ctx context.Context, in *GetPayloadRequest, opts ...grpc.CallOption) (*GetPayloadResponse, error)
	StreamHeader(ctx context.Context, in *StreamHeaderRequest, opts ...grpc.CallOption) (RelayProxy_StreamHeaderClient, error)
}

type relayProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayProxyClient(cc grpc.ClientConnInterface) RelayProxyClient {
	return &relayProxyClient{cc}
}

func (c *relayProxyClient) RegisterValidator(ctx context.Context, in *RegisterValidatorRequest, opts ...grpc.CallOption) (*RegisterValidatorResponse, error) {
	out := new(RegisterValidatorResponse)
	err := c.cc.Invoke(ctx, RelayProxy_RegisterValidator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayProxyClient) GetHeader(ctx context.Context, in *GetHeaderRequest, opts ...grpc.CallOption) (*GetHeaderResponse, error) {
	out := new(GetHeaderResponse)
	err := c.cc.Invoke(ctx, RelayProxy_GetHeader_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayProxyClient) GetPayload(ctx context.Context, in *GetPayloadRequest, opts ...grpc.CallOption) (*GetPayloadResponse, error) {
	out := new(GetPayloadResponse)
	err := c.cc.Invoke(ctx, RelayProxy_GetPayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayProxyClient) StreamHeader(ctx context.Context, in *StreamHeaderRequest, opts ...grpc.CallOption) (RelayProxy_StreamHeaderClient, error) {
	stream, err := c.cc.NewStream(ctx, &RelayProxy_ServiceDesc.Streams[0], RelayProxy_StreamHeader_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &relayProxyStreamHeaderClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RelayProxy_StreamHeaderClient interface {
	Recv() (*StreamHeaderResponse, error)
	grpc.ClientStream
}

type relayProxyStreamHeaderClient struct {
	grpc.ClientStream
}

func (x *relayProxyStreamHeaderClient) Recv() (*StreamHeaderResponse, error) {
	m := new(StreamHeaderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RelayProxyServer is the server API for RelayProxy service.
// All implementations must embed UnimplementedRelayProxyServer
// for forward compatibility
type RelayProxyServer interface {
	RegisterValidator(context.Context, *RegisterValidatorRequest) (*RegisterValidatorResponse, error)
	GetHeader(context.Context, *GetHeaderRequest) (*GetHeaderResponse, error)
	GetPayload(context.Context, *GetPayloadRequest) (*GetPayloadResponse, error)
	StreamHeader(*StreamHeaderRequest, RelayProxy_StreamHeaderServer) error
	mustEmbedUnimplementedRelayProxyServer()
}

// UnimplementedRelayProxyServer must be embedded to have forward compatible implementations.
type UnimplementedRelayProxyServer struct {
}

func (UnimplementedRelayProxyServer) RegisterValidator(context.Context, *RegisterValidatorRequest) (*RegisterValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterValidator not implemented")
}
func (UnimplementedRelayProxyServer) GetHeader(context.Context, *GetHeaderRequest) (*GetHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHeader not implemented")
}
func (UnimplementedRelayProxyServer) GetPayload(context.Context, *GetPayloadRequest) (*GetPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayload not implemented")
}
func (UnimplementedRelayProxyServer) StreamHeader(*StreamHeaderRequest, RelayProxy_StreamHeaderServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamHeader not implemented")
}
func (UnimplementedRelayProxyServer) mustEmbedUnimplementedRelayProxyServer() {}

// UnsafeRelayProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayProxyServer will
// result in compilation errors.
type UnsafeRelayProxyServer interface {
	mustEmbedUnimplementedRelayProxyServer()
}

func RegisterRelayProxyServer(s grpc.ServiceRegistrar, srv RelayProxyServer) {
	s.RegisterService(&RelayProxy_ServiceDesc, srv)
}

func _RelayProxy_RegisterValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayProxyServer).RegisterValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayProxy_RegisterValidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayProxyServer).RegisterValidator(ctx, req.(*RegisterValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayProxy_GetHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayProxyServer).GetHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayProxy_GetHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayProxyServer).GetHeader(ctx, req.(*GetHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayProxy_GetPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayProxyServer).GetPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayProxy_GetPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayProxyServer).GetPayload(ctx, req.(*GetPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayProxy_StreamHeader_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamHeaderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RelayProxyServer).StreamHeader(m, &relayProxyStreamHeaderServer{stream})
}

type RelayProxy_StreamHeaderServer interface {
	Send(*StreamHeaderResponse) error
	grpc.ServerStream
}

type relayProxyStreamHeaderServer struct {
	grpc.ServerStream
}

func (x *relayProxyStreamHeaderServer) Send(m *StreamHeaderResponse) error {
	return x.ServerStream.SendMsg(m)
}

// RelayProxy_ServiceDesc is the grpc.ServiceDesc for RelayProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RelayProxy",
	HandlerType: (*RelayProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterValidator",
			Handler:    _RelayProxy_RegisterValidator_Handler,
		},
		{
			MethodName: "GetHeader",
			Handler:    _RelayProxy_GetHeader_Handler,
		},
		{
			MethodName: "GetPayload",
			Handler:    _RelayProxy_GetPayload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHeader",
			Handler:       _RelayProxy_StreamHeader_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "relay-proxy.proto",
}
