// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    #[prost(string, tag="1")]
    pub message: ::prost::alloc::string::String,
}
/// Registration
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterValidatorRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub version: ::prost::alloc::string::String,
    /// validators are registering via relay proxy is trusted so no need auth header for now
    #[prost(string, tag="6")]
    pub auth_header: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub secret_token: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="9")]
    pub compliance_list: ::prost::alloc::string::String,
    #[prost(bool, tag="10")]
    pub proposer_mev_protect: bool,
    #[prost(bool, tag="11")]
    pub skip_optimism: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterValidatorResponse {
    #[prost(uint32, tag="1")]
    pub code: u32,
    /// added for http api compatibility
    #[prost(int32, tag="2")]
    pub http_status_code: i32,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetValidatorRegistrationRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub secret_token: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub account_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetValidatorRegistrationResponse {
    #[prost(uint32, tag="1")]
    pub code: u32,
    #[prost(int32, tag="2")]
    pub http_status_code: i32,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// GetHeader
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetHeaderRequest {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetHeaderResponse {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub code: u32,
    /// added for http api compatibility
    #[prost(int32, tag="3")]
    pub http_status_code: i32,
    #[prost(uint64, tag="4")]
    pub slot: u64,
    #[prost(string, tag="5")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="7")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// GetPayload
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPayloadRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub secret_token: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPayloadResponse {
    #[prost(uint32, tag="1")]
    pub code: u32,
    /// added for http api compatibility
    #[prost(int32, tag="2")]
    pub http_status_code: i32,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub ssz_versioned_execution_payload: ::prost::alloc::vec::Vec<u8>,
    /// below fields not needed but added for logging on the relay proxy
    #[prost(uint64, tag="5")]
    pub slot: u64,
    #[prost(string, tag="6")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub proposer_index: u64,
    #[prost(string, tag="10")]
    pub block_value: ::prost::alloc::string::String,
}
/// StreamHeader
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamHeaderRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub secret_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamHeaderResponse {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// value field added to avoid unmarshalling payload which contains value
    #[prost(bytes="vec", tag="5")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// head slot added for cleaning up old slot
    #[prost(uint64, tag="6")]
    pub head_slot: u64,
    #[prost(string, tag="7")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub builder_pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub builder_extra_data: ::prost::alloc::string::String,
    #[prost(message, optional, tag="10")]
    pub send_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="11")]
    pub paid_blxr: bool,
    #[prost(message, optional, tag="12")]
    pub relay_receive_time: ::core::option::Option<::prost_types::Timestamp>,
    /// account ID of the BUILDER
    #[prost(string, tag="13")]
    pub account_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="14")]
    pub bid_trace: ::core::option::Option<BidTrace>,
    #[prost(message, optional, tag="15")]
    pub execution_payload_header: ::core::option::Option<ExecutionPayloadHeader>,
    #[prost(bytes="vec", repeated, tag="16")]
    pub commitments: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="17")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="18")]
    pub tx_count: u64,
    #[prost(message, optional, tag="19")]
    pub execution_requests: ::core::option::Option<ExecutionRequests>,
    #[prost(string, tag="20")]
    pub payload_fetch_url: ::prost::alloc::string::String,
    #[prost(uint64, tag="21")]
    pub block_sequence_number: u64,
    #[prost(bool, tag="22")]
    pub hidden: bool,
    #[prost(string, tag="23")]
    pub original_submission_method: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="24")]
    pub ssz_adjustment_data: ::prost::alloc::vec::Vec<u8>,
    /// IP of the builder that originally submitted the block
    #[prost(string, tag="25")]
    pub builder_ip: ::prost::alloc::string::String,
    /// Original region the block was submitted to
    #[prost(string, tag="26")]
    pub block_submission_region: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamBlockRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub secret_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamBlockResponse {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub grpc_payload: ::core::option::Option<SubmitBlockRequest>,
    /// value field added to avoid unmarshalling payload which contains value
    #[prost(bytes="vec", tag="6")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// head slot added for cleaning up old slot
    #[prost(uint64, tag="7")]
    pub head_slot: u64,
    #[prost(string, tag="8")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub builder_pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub builder_extra_data: ::prost::alloc::string::String,
    #[prost(message, optional, tag="11")]
    pub send_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="12")]
    pub paid_blxr: bool,
    #[prost(message, optional, tag="13")]
    pub relay_receive_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="14")]
    pub account_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreFetchGetPayloadRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub secret_token: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub slot: u64,
    #[prost(string, tag="5")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreFetchGetPayloadResponse {
    #[prost(uint32, tag="1")]
    pub code: u32,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub ssz_versioned_execution_payload: ::prost::alloc::vec::Vec<u8>,
}
/// SubmitBlock
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitBlockRequest {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(message, optional, tag="2")]
    pub bid_trace: ::core::option::Option<BidTrace>,
    #[prost(message, optional, tag="3")]
    pub execution_payload: ::core::option::Option<ExecutionPayload>,
    #[prost(bytes="vec", tag="4")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub auth_header: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub size_before: u64,
    #[prost(bool, tag="7")]
    pub get_payload_only: bool,
    #[prost(message, optional, tag="8")]
    pub blobs_bundle: ::core::option::Option<BlobsBundle>,
    #[prost(bool, tag="9")]
    pub second_value_auction_eligible: bool,
    #[prost(bool, tag="10")]
    pub proposer_mev_protect: bool,
    #[prost(bool, tag="11")]
    pub skip_optimism: bool,
    #[prost(bool, tag="12")]
    pub compliance_list: bool,
    #[prost(bytes="vec", tag="13")]
    pub adjustment_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="14")]
    pub execution_requests: ::core::option::Option<ExecutionRequests>,
    #[prost(bool, tag="15")]
    pub get_payload_only_builder_requested: bool,
    #[prost(bool, tag="16")]
    pub get_payload_only_region_locked: bool,
    #[prost(bool, tag="17")]
    pub get_payload_only_no_adjustment_data: bool,
    #[prost(uint64, tag="18")]
    pub block_sequence_number: u64,
    #[prost(bool, tag="19")]
    pub hidden: bool,
    #[prost(bool, tag="20")]
    pub hydrate: bool,
    /// IP of the builder that originally submitted the block
    #[prost(string, tag="21")]
    pub builder_ip: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HydrateBlobItem {
    #[prost(bytes="vec", tag="1")]
    pub commitment: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub proofs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="3")]
    pub blob: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitBlockResponse {
    #[prost(int64, tag="1")]
    pub code: i64,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BidTrace {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(bytes="vec", tag="2")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub builder_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub proposer_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub proposer_fee_recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub blob_gas_used: u64,
    #[prost(uint64, tag="11")]
    pub excess_blob_gas: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Withdrawal {
    #[prost(uint64, tag="1")]
    pub index: u64,
    #[prost(uint64, tag="2")]
    pub validator_index: u64,
    #[prost(bytes="vec", tag="3")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub amount: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobsBundle {
    #[prost(bytes="vec", repeated, tag="1")]
    pub commitments: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub proofs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub blobs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag="4")]
    pub new_items: ::prost::alloc::vec::Vec<HydrateBlobItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionPayload {
    #[prost(bytes="vec", tag="1")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub receipts_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub logs_bloom: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub prev_randao: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub extra_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub base_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub fee_recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag="10")]
    pub transactions: ::prost::alloc::vec::Vec<CompressTx>,
    #[prost(message, repeated, tag="11")]
    pub withdrawals: ::prost::alloc::vec::Vec<Withdrawal>,
    #[prost(uint64, tag="12")]
    pub block_number: u64,
    #[prost(uint64, tag="13")]
    pub gas_limit: u64,
    #[prost(uint64, tag="14")]
    pub timestamp: u64,
    #[prost(uint64, tag="15")]
    pub gas_used: u64,
    #[prost(uint64, tag="16")]
    pub blob_gas_used: u64,
    #[prost(uint64, tag="17")]
    pub excess_blob_gas: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecutionPayloadHeader {
    #[prost(bytes="vec", tag="1")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub receipts_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub logs_bloom: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub prev_randao: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub extra_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub base_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub fee_recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub transactions_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub withdrawals_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub block_number: u64,
    #[prost(uint64, tag="13")]
    pub gas_limit: u64,
    #[prost(uint64, tag="14")]
    pub timestamp: u64,
    #[prost(uint64, tag="15")]
    pub gas_used: u64,
    #[prost(uint64, tag="16")]
    pub blob_gas_used: u64,
    #[prost(uint64, tag="17")]
    pub excess_blob_gas: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompressTx {
    #[prost(bytes="vec", tag="1")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub short_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionRequests {
    #[prost(message, repeated, tag="1")]
    pub deposits: ::prost::alloc::vec::Vec<DepositRequest>,
    #[prost(message, repeated, tag="2")]
    pub withdrawals: ::prost::alloc::vec::Vec<WithdrawalRequest>,
    #[prost(message, repeated, tag="3")]
    pub consolidations: ::prost::alloc::vec::Vec<ConsolidationRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DepositRequest {
    #[prost(bytes="vec", tag="1")]
    pub pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub withdrawal_credentials: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub amount: u64,
    #[prost(bytes="vec", tag="4")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub index: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WithdrawalRequest {
    #[prost(bytes="vec", tag="1")]
    pub source_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub validator_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub amount: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsolidationRequest {
    #[prost(bytes="vec", tag="1")]
    pub source_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub source_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub target_pubkey: ::prost::alloc::vec::Vec<u8>,
}
/// StreamBuilder
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamBuilderRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamBuilderResponse {
    #[prost(message, repeated, tag="1")]
    pub builder_info: ::prost::alloc::vec::Vec<BuilderInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuilderInfo {
    #[prost(bytes="vec", tag="1")]
    pub builder_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="2")]
    pub is_optimistic: bool,
    #[prost(bool, tag="3")]
    pub is_demoted: bool,
    #[prost(string, tag="4")]
    pub external_builder_account_id: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub is_builder_pubkey_high_priority: bool,
    #[prost(bytes="vec", tag="6")]
    pub builder_pubkey_skip_simulation_threshold: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="7")]
    pub is_builder_account_id_high_priority: bool,
    #[prost(bytes="vec", tag="8")]
    pub builder_account_id_skip_simulation_threshold: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="9")]
    pub trusted_external_builder: bool,
    #[prost(bool, tag="10")]
    pub is_opted_in: bool,
    #[prost(message, repeated, tag="11")]
    pub wallet_accounts: ::prost::alloc::vec::Vec<WalletAccount>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WalletAccount {
    #[prost(bytes="vec", tag="1")]
    pub pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub nonce: u64,
    #[prost(bytes="vec", tag="3")]
    pub balance: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub last_updated_block: u64,
}
/// StreamSlot
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamSlotRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamSlotResponse {
    #[prost(bytes="vec", tag="1")]
    pub proposer_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub proposer_fee_recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub slot: u64,
    #[prost(bool, tag="4")]
    pub is_eoa: bool,
    #[prost(uint64, tag="5")]
    pub last_updated_block: u64,
    #[prost(bytes="vec", tag="6")]
    pub parent_block_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub parent_block_hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeaderDeliveredRequest {
    #[prost(int64, tag="1")]
    pub id: i64,
    #[prost(message, optional, tag="2")]
    pub inserted_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="3")]
    pub header_request_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub slot: u64,
    #[prost(uint64, tag="5")]
    pub epoch: u64,
    #[prost(string, tag="6")]
    pub builder_pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub proposer_pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub proposer_fee_recipient: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub block_number: u64,
    #[prost(string, tag="12")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub value_eth: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub proposer_send_timestamp_ms: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub extra_data: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeaderDeliveredResponse {
    #[prost(string, tag="1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdjustLatestBlockPayloadRequest {
    #[prost(string, tag="1")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub secret_token: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub slot: u64,
    #[prost(string, tag="5")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdjustLatestBlockPayloadResponse {
    #[prost(uint32, tag="1")]
    pub code: u32,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
    #[prost(message, optional, tag="4")]
    pub signed_builder_bid: ::core::option::Option<SignedBuilderBid>,
    #[prost(message, optional, tag="5")]
    pub bid_trace: ::core::option::Option<BidTrace>,
    #[prost(string, tag="6")]
    pub extra_data: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub external_builder_account_id: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub payload_fetch_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignedBuilderBid {
    #[prost(message, optional, tag="1")]
    pub builder_bid: ::core::option::Option<BuilderBid>,
    #[prost(bytes="vec", tag="2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuilderBid {
    #[prost(message, optional, tag="1")]
    pub execution_payload_header: ::core::option::Option<ExecutionPayloadHeader>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub commitments: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag="3")]
    pub execution_requests: ::core::option::Option<ExecutionRequests>,
    #[prost(string, tag="4")]
    pub value: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub pubkey: ::prost::alloc::vec::Vec<u8>,
}
include!("blxrmev.tonic.rs");
// @@protoc_insertion_point(module)
