// Code generated by fastssz. DO NOT EDIT.
// Hash: 9f69a5d7f3e1bffe8ddbdf09b9a258103a106f5404f871d2291c9f6bf726423b
// Version: 0.1.3
package optimisticv3

import (
	v1 "github.com/attestantio/go-builder-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionV3 object to a target array
func (h *HeaderSubmissionV3) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'URL'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(h.URL)

	// Field (1) 'TxCount'
	dst = ssz.MarshalUint32(dst, h.TxCount)

	// Field (2) 'Submission'
	if h.Submission == nil {
		h.Submission = new(VersionedSignedHeaderSubmission)
	}
	if dst, err = h.Submission.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (0) 'URL'
	if size := len(h.URL); size > 256 {
		err = ssz.ErrBytesLengthFn("HeaderSubmissionV3.URL", size, 256)
		return
	}
	dst = append(dst, h.URL...)

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'URL'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'TxCount'
	h.TxCount = ssz.UnmarshallUint32(buf[4:8])

	// Field (2) 'Submission'
	if h.Submission == nil {
		h.Submission = new(VersionedSignedHeaderSubmission)
	}
	if err = h.Submission.UnmarshalSSZ(buf[8:8]); err != nil {
		return err
	}

	// Field (0) 'URL'
	{
		buf = tail[o0:]
		if len(buf) > 256 {
			return ssz.ErrBytesLength
		}
		if cap(h.URL) == 0 {
			h.URL = make([]byte, 0, len(buf))
		}
		h.URL = append(h.URL, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'URL'
	size += len(h.URL)

	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionV3 object with a hasher
func (h *HeaderSubmissionV3) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'URL'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(h.URL))
		if byteLen > 256 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(h.URL)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (256+31)/32)
	}

	// Field (1) 'TxCount'
	hh.PutUint32(h.TxCount)

	// Field (2) 'Submission'
	if h.Submission == nil {
		h.Submission = new(VersionedSignedHeaderSubmission)
	}
	if err = h.Submission.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the VersionedSignedHeaderSubmission object to a target array
func (v *VersionedSignedHeaderSubmission) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	return
}

// UnmarshalSSZ ssz unmarshals the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 0 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) SizeSSZ() (size int) {
	size = 0
	return
}

// HashTreeRoot ssz hashes the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the VersionedSignedHeaderSubmission object with a hasher
func (v *VersionedSignedHeaderSubmission) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}

// MarshalSSZ ssz marshals the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedHeaderSubmissionDeneb object to a target array
func (s *SignedHeaderSubmissionDeneb) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)
	offset += s.Message.SizeSSZ()

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[4:100])

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedHeaderSubmissionDeneb object with a hasher
func (s *SignedHeaderSubmissionDeneb) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedHeaderSubmissionElectra object to a target array
func (s *SignedHeaderSubmissionElectra) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)
	offset += s.Message.SizeSSZ()

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[4:100])

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedHeaderSubmissionElectra object with a hasher
func (s *SignedHeaderSubmissionElectra) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionDenebV2 object to a target array
func (h *HeaderSubmissionDenebV2) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(244)

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if dst, err = h.BidTrace.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'ExecutionPayloadHeader'
	dst = ssz.WriteOffset(dst, offset)
	if h.ExecutionPayloadHeader == nil {
		h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	offset += h.ExecutionPayloadHeader.SizeSSZ()

	// Offset (2) 'Commitments'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(h.Commitments) * 48

	// Field (1) 'ExecutionPayloadHeader'
	if dst, err = h.ExecutionPayloadHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'Commitments'
	if size := len(h.Commitments); size > 4096 {
		err = ssz.ErrListTooBigFn("HeaderSubmissionDenebV2.Commitments", size, 4096)
		return
	}
	for ii := 0; ii < len(h.Commitments); ii++ {
		dst = append(dst, h.Commitments[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 244 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2 uint64

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if err = h.BidTrace.UnmarshalSSZ(buf[0:236]); err != nil {
		return err
	}

	// Offset (1) 'ExecutionPayloadHeader'
	if o1 = ssz.ReadOffset(buf[236:240]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 < 244 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'Commitments'
	if o2 = ssz.ReadOffset(buf[240:244]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (1) 'ExecutionPayloadHeader'
	{
		buf = tail[o1:o2]
		if h.ExecutionPayloadHeader == nil {
			h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
		}
		if err = h.ExecutionPayloadHeader.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'Commitments'
	{
		buf = tail[o2:]
		num, err := ssz.DivideInt2(len(buf), 48, 4096)
		if err != nil {
			return err
		}
		h.Commitments = make([][48]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(h.Commitments[ii][:], buf[ii*48:(ii+1)*48])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) SizeSSZ() (size int) {
	size = 244

	// Field (1) 'ExecutionPayloadHeader'
	if h.ExecutionPayloadHeader == nil {
		h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	size += h.ExecutionPayloadHeader.SizeSSZ()

	// Field (2) 'Commitments'
	size += len(h.Commitments) * 48

	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionDenebV2 object with a hasher
func (h *HeaderSubmissionDenebV2) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if err = h.BidTrace.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'ExecutionPayloadHeader'
	if err = h.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Commitments'
	{
		if size := len(h.Commitments); size > 4096 {
			err = ssz.ErrListTooBigFn("HeaderSubmissionDenebV2.Commitments", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range h.Commitments {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(h.Commitments))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionElectra object to a target array
func (h *HeaderSubmissionElectra) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(252)

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if dst, err = h.BidTrace.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'ExecutionPayloadHeader'
	dst = ssz.WriteOffset(dst, offset)
	if h.ExecutionPayloadHeader == nil {
		h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	offset += h.ExecutionPayloadHeader.SizeSSZ()

	// Offset (2) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	if h.ExecutionRequests == nil {
		h.ExecutionRequests = new(electra.ExecutionRequests)
	}
	offset += h.ExecutionRequests.SizeSSZ()

	// Offset (3) 'Commitments'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(h.Commitments) * 48

	// Offset (4) 'AdjustmentData'
	dst = ssz.WriteOffset(dst, offset)
	offset += h.AdjustmentData.SizeSSZ()

	// Field (1) 'ExecutionPayloadHeader'
	if dst, err = h.ExecutionPayloadHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'ExecutionRequests'
	if dst, err = h.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'Commitments'
	if size := len(h.Commitments); size > 4096 {
		err = ssz.ErrListTooBigFn("HeaderSubmissionElectra.Commitments", size, 4096)
		return
	}
	for ii := 0; ii < len(h.Commitments); ii++ {
		dst = append(dst, h.Commitments[ii][:]...)
	}

	// Field (4) 'AdjustmentData'
	if dst, err = h.AdjustmentData.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 252 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2, o3, o4 uint64

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if err = h.BidTrace.UnmarshalSSZ(buf[0:236]); err != nil {
		return err
	}

	// Offset (1) 'ExecutionPayloadHeader'
	if o1 = ssz.ReadOffset(buf[236:240]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 < 252 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'ExecutionRequests'
	if o2 = ssz.ReadOffset(buf[240:244]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'Commitments'
	if o3 = ssz.ReadOffset(buf[244:248]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Offset (4) 'AdjustmentData'
	if o4 = ssz.ReadOffset(buf[248:252]); o4 > size || o3 > o4 {
		return ssz.ErrOffset
	}

	// Field (1) 'ExecutionPayloadHeader'
	{
		buf = tail[o1:o2]
		if h.ExecutionPayloadHeader == nil {
			h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
		}
		if err = h.ExecutionPayloadHeader.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'ExecutionRequests'
	{
		buf = tail[o2:o3]
		if h.ExecutionRequests == nil {
			h.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = h.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (3) 'Commitments'
	{
		buf = tail[o3:o4]
		num, err := ssz.DivideInt2(len(buf), 48, 4096)
		if err != nil {
			return err
		}
		h.Commitments = make([][48]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(h.Commitments[ii][:], buf[ii*48:(ii+1)*48])
		}
	}

	// Field (4) 'AdjustmentData'
	{
		buf = tail[o4:]
		if err = h.AdjustmentData.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) SizeSSZ() (size int) {
	size = 252

	// Field (1) 'ExecutionPayloadHeader'
	if h.ExecutionPayloadHeader == nil {
		h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	size += h.ExecutionPayloadHeader.SizeSSZ()

	// Field (2) 'ExecutionRequests'
	if h.ExecutionRequests == nil {
		h.ExecutionRequests = new(electra.ExecutionRequests)
	}
	size += h.ExecutionRequests.SizeSSZ()

	// Field (3) 'Commitments'
	size += len(h.Commitments) * 48

	// Field (4) 'AdjustmentData'
	size += h.AdjustmentData.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionElectra object with a hasher
func (h *HeaderSubmissionElectra) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if err = h.BidTrace.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'ExecutionPayloadHeader'
	if err = h.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'ExecutionRequests'
	if err = h.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'Commitments'
	{
		if size := len(h.Commitments); size > 4096 {
			err = ssz.ErrListTooBigFn("HeaderSubmissionElectra.Commitments", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range h.Commitments {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(h.Commitments))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	// Field (4) 'AdjustmentData'
	if err = h.AdjustmentData.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the GetPayloadV3 object
func (g *GetPayloadV3) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV3 object to a target array
func (g *GetPayloadV3) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'BlockHash'
	dst = append(dst, g.BlockHash[:]...)

	// Field (1) 'RequestTs'
	dst = ssz.MarshalUint64(dst, g.RequestTs)

	// Field (2) 'RelayPublicKey'
	dst = append(dst, g.RelayPublicKey[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV3 object
func (g *GetPayloadV3) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 88 {
		return ssz.ErrSize
	}

	// Field (0) 'BlockHash'
	copy(g.BlockHash[:], buf[0:32])

	// Field (1) 'RequestTs'
	g.RequestTs = ssz.UnmarshallUint64(buf[32:40])

	// Field (2) 'RelayPublicKey'
	copy(g.RelayPublicKey[:], buf[40:88])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV3 object
func (g *GetPayloadV3) SizeSSZ() (size int) {
	size = 88
	return
}

// HashTreeRoot ssz hashes the GetPayloadV3 object
func (g *GetPayloadV3) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV3 object with a hasher
func (g *GetPayloadV3) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'BlockHash'
	hh.PutBytes(g.BlockHash[:])

	// Field (1) 'RequestTs'
	hh.PutUint64(g.RequestTs)

	// Field (2) 'RelayPublicKey'
	hh.PutBytes(g.RelayPublicKey[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the GetPayloadV3 object
func (g *GetPayloadV3) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(g)
}

// MarshalSSZ ssz marshals the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedGetPayloadV3 object to a target array
func (s *SignedGetPayloadV3) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(GetPayloadV3)
	}
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 184 {
		return ssz.ErrSize
	}

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(GetPayloadV3)
	}
	if err = s.Message.UnmarshalSSZ(buf[0:88]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[88:184])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) SizeSSZ() (size int) {
	size = 184
	return
}

// HashTreeRoot ssz hashes the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedGetPayloadV3 object with a hasher
func (s *SignedGetPayloadV3) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(GetPayloadV3)
	}
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the AdjustmentDataV2 object
func (a *AdjustmentDataV2) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AdjustmentDataV2 object to a target array
func (a *AdjustmentDataV2) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(404)

	// Field (0) 'ELTransactionsRoot'
	dst = append(dst, a.ELTransactionsRoot[:]...)

	// Field (1) 'ELWithdrawalsRoot'
	dst = append(dst, a.ELWithdrawalsRoot[:]...)

	// Field (2) 'BuilderAddress'
	dst = append(dst, a.BuilderAddress[:]...)

	// Offset (3) 'BuilderProof'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(a.BuilderProof); ii++ {
		offset += 4
		offset += len(a.BuilderProof[ii])
	}

	// Field (4) 'FeeRecipientAddress'
	dst = append(dst, a.FeeRecipientAddress[:]...)

	// Offset (5) 'FeeRecipientProof'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(a.FeeRecipientProof); ii++ {
		offset += 4
		offset += len(a.FeeRecipientProof[ii])
	}

	// Field (6) 'FeePayerAddress'
	dst = append(dst, a.FeePayerAddress[:]...)

	// Offset (7) 'FeePayerProof'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(a.FeePayerProof); ii++ {
		offset += 4
		offset += len(a.FeePayerProof[ii])
	}

	// Offset (8) 'ELPlaceholderTxProof'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(a.ELPlaceholderTxProof); ii++ {
		offset += 4
		offset += len(a.ELPlaceholderTxProof[ii])
	}

	// Offset (9) 'CLPlaceholderTxProof'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.CLPlaceholderTxProof) * 32

	// Offset (10) 'PlaceholderReceiptProof'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(a.PlaceholderReceiptProof); ii++ {
		offset += 4
		offset += len(a.PlaceholderReceiptProof[ii])
	}

	// Field (11) 'PrePaymentLogsBloom'
	dst = append(dst, a.PrePaymentLogsBloom[:]...)

	// Field (3) 'BuilderProof'
	if size := len(a.BuilderProof); size > 64 {
		err = ssz.ErrListTooBigFn("AdjustmentDataV2.BuilderProof", size, 64)
		return
	}
	{
		offset = 4 * len(a.BuilderProof)
		for ii := 0; ii < len(a.BuilderProof); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(a.BuilderProof[ii])
		}
	}
	for ii := 0; ii < len(a.BuilderProof); ii++ {
		if size := len(a.BuilderProof[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("AdjustmentDataV2.BuilderProof[ii]", size, 1073741824)
			return
		}
		dst = append(dst, a.BuilderProof[ii]...)
	}

	// Field (5) 'FeeRecipientProof'
	if size := len(a.FeeRecipientProof); size > 64 {
		err = ssz.ErrListTooBigFn("AdjustmentDataV2.FeeRecipientProof", size, 64)
		return
	}
	{
		offset = 4 * len(a.FeeRecipientProof)
		for ii := 0; ii < len(a.FeeRecipientProof); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(a.FeeRecipientProof[ii])
		}
	}
	for ii := 0; ii < len(a.FeeRecipientProof); ii++ {
		if size := len(a.FeeRecipientProof[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("AdjustmentDataV2.FeeRecipientProof[ii]", size, 1073741824)
			return
		}
		dst = append(dst, a.FeeRecipientProof[ii]...)
	}

	// Field (7) 'FeePayerProof'
	if size := len(a.FeePayerProof); size > 64 {
		err = ssz.ErrListTooBigFn("AdjustmentDataV2.FeePayerProof", size, 64)
		return
	}
	{
		offset = 4 * len(a.FeePayerProof)
		for ii := 0; ii < len(a.FeePayerProof); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(a.FeePayerProof[ii])
		}
	}
	for ii := 0; ii < len(a.FeePayerProof); ii++ {
		if size := len(a.FeePayerProof[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("AdjustmentDataV2.FeePayerProof[ii]", size, 1073741824)
			return
		}
		dst = append(dst, a.FeePayerProof[ii]...)
	}

	// Field (8) 'ELPlaceholderTxProof'
	if size := len(a.ELPlaceholderTxProof); size > 64 {
		err = ssz.ErrListTooBigFn("AdjustmentDataV2.ELPlaceholderTxProof", size, 64)
		return
	}
	{
		offset = 4 * len(a.ELPlaceholderTxProof)
		for ii := 0; ii < len(a.ELPlaceholderTxProof); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(a.ELPlaceholderTxProof[ii])
		}
	}
	for ii := 0; ii < len(a.ELPlaceholderTxProof); ii++ {
		if size := len(a.ELPlaceholderTxProof[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("AdjustmentDataV2.ELPlaceholderTxProof[ii]", size, 1073741824)
			return
		}
		dst = append(dst, a.ELPlaceholderTxProof[ii]...)
	}

	// Field (9) 'CLPlaceholderTxProof'
	if size := len(a.CLPlaceholderTxProof); size > 1073741824 {
		err = ssz.ErrListTooBigFn("AdjustmentDataV2.CLPlaceholderTxProof", size, 1073741824)
		return
	}
	for ii := 0; ii < len(a.CLPlaceholderTxProof); ii++ {
		dst = append(dst, a.CLPlaceholderTxProof[ii][:]...)
	}

	// Field (10) 'PlaceholderReceiptProof'
	if size := len(a.PlaceholderReceiptProof); size > 64 {
		err = ssz.ErrListTooBigFn("AdjustmentDataV2.PlaceholderReceiptProof", size, 64)
		return
	}
	{
		offset = 4 * len(a.PlaceholderReceiptProof)
		for ii := 0; ii < len(a.PlaceholderReceiptProof); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(a.PlaceholderReceiptProof[ii])
		}
	}
	for ii := 0; ii < len(a.PlaceholderReceiptProof); ii++ {
		if size := len(a.PlaceholderReceiptProof[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("AdjustmentDataV2.PlaceholderReceiptProof[ii]", size, 1073741824)
			return
		}
		dst = append(dst, a.PlaceholderReceiptProof[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the AdjustmentDataV2 object
func (a *AdjustmentDataV2) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 404 {
		return ssz.ErrSize
	}

	tail := buf
	var o3, o5, o7, o8, o9, o10 uint64

	// Field (0) 'ELTransactionsRoot'
	copy(a.ELTransactionsRoot[:], buf[0:32])

	// Field (1) 'ELWithdrawalsRoot'
	copy(a.ELWithdrawalsRoot[:], buf[32:64])

	// Field (2) 'BuilderAddress'
	copy(a.BuilderAddress[:], buf[64:84])

	// Offset (3) 'BuilderProof'
	if o3 = ssz.ReadOffset(buf[84:88]); o3 > size {
		return ssz.ErrOffset
	}

	if o3 < 404 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (4) 'FeeRecipientAddress'
	copy(a.FeeRecipientAddress[:], buf[88:108])

	// Offset (5) 'FeeRecipientProof'
	if o5 = ssz.ReadOffset(buf[108:112]); o5 > size || o3 > o5 {
		return ssz.ErrOffset
	}

	// Field (6) 'FeePayerAddress'
	copy(a.FeePayerAddress[:], buf[112:132])

	// Offset (7) 'FeePayerProof'
	if o7 = ssz.ReadOffset(buf[132:136]); o7 > size || o5 > o7 {
		return ssz.ErrOffset
	}

	// Offset (8) 'ELPlaceholderTxProof'
	if o8 = ssz.ReadOffset(buf[136:140]); o8 > size || o7 > o8 {
		return ssz.ErrOffset
	}

	// Offset (9) 'CLPlaceholderTxProof'
	if o9 = ssz.ReadOffset(buf[140:144]); o9 > size || o8 > o9 {
		return ssz.ErrOffset
	}

	// Offset (10) 'PlaceholderReceiptProof'
	if o10 = ssz.ReadOffset(buf[144:148]); o10 > size || o9 > o10 {
		return ssz.ErrOffset
	}

	// Field (11) 'PrePaymentLogsBloom'
	copy(a.PrePaymentLogsBloom[:], buf[148:404])

	// Field (3) 'BuilderProof'
	{
		buf = tail[o3:o5]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		a.BuilderProof = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(a.BuilderProof[indx]) == 0 {
				a.BuilderProof[indx] = make([]byte, 0, len(buf))
			}
			a.BuilderProof[indx] = append(a.BuilderProof[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (5) 'FeeRecipientProof'
	{
		buf = tail[o5:o7]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		a.FeeRecipientProof = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(a.FeeRecipientProof[indx]) == 0 {
				a.FeeRecipientProof[indx] = make([]byte, 0, len(buf))
			}
			a.FeeRecipientProof[indx] = append(a.FeeRecipientProof[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (7) 'FeePayerProof'
	{
		buf = tail[o7:o8]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		a.FeePayerProof = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(a.FeePayerProof[indx]) == 0 {
				a.FeePayerProof[indx] = make([]byte, 0, len(buf))
			}
			a.FeePayerProof[indx] = append(a.FeePayerProof[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (8) 'ELPlaceholderTxProof'
	{
		buf = tail[o8:o9]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		a.ELPlaceholderTxProof = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(a.ELPlaceholderTxProof[indx]) == 0 {
				a.ELPlaceholderTxProof[indx] = make([]byte, 0, len(buf))
			}
			a.ELPlaceholderTxProof[indx] = append(a.ELPlaceholderTxProof[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (9) 'CLPlaceholderTxProof'
	{
		buf = tail[o9:o10]
		num, err := ssz.DivideInt2(len(buf), 32, 1073741824)
		if err != nil {
			return err
		}
		a.CLPlaceholderTxProof = make([][32]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(a.CLPlaceholderTxProof[ii][:], buf[ii*32:(ii+1)*32])
		}
	}

	// Field (10) 'PlaceholderReceiptProof'
	{
		buf = tail[o10:]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		a.PlaceholderReceiptProof = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(a.PlaceholderReceiptProof[indx]) == 0 {
				a.PlaceholderReceiptProof[indx] = make([]byte, 0, len(buf))
			}
			a.PlaceholderReceiptProof[indx] = append(a.PlaceholderReceiptProof[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AdjustmentDataV2 object
func (a *AdjustmentDataV2) SizeSSZ() (size int) {
	size = 404

	// Field (3) 'BuilderProof'
	for ii := 0; ii < len(a.BuilderProof); ii++ {
		size += 4
		size += len(a.BuilderProof[ii])
	}

	// Field (5) 'FeeRecipientProof'
	for ii := 0; ii < len(a.FeeRecipientProof); ii++ {
		size += 4
		size += len(a.FeeRecipientProof[ii])
	}

	// Field (7) 'FeePayerProof'
	for ii := 0; ii < len(a.FeePayerProof); ii++ {
		size += 4
		size += len(a.FeePayerProof[ii])
	}

	// Field (8) 'ELPlaceholderTxProof'
	for ii := 0; ii < len(a.ELPlaceholderTxProof); ii++ {
		size += 4
		size += len(a.ELPlaceholderTxProof[ii])
	}

	// Field (9) 'CLPlaceholderTxProof'
	size += len(a.CLPlaceholderTxProof) * 32

	// Field (10) 'PlaceholderReceiptProof'
	for ii := 0; ii < len(a.PlaceholderReceiptProof); ii++ {
		size += 4
		size += len(a.PlaceholderReceiptProof[ii])
	}

	return
}

// HashTreeRoot ssz hashes the AdjustmentDataV2 object
func (a *AdjustmentDataV2) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AdjustmentDataV2 object with a hasher
func (a *AdjustmentDataV2) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ELTransactionsRoot'
	hh.PutBytes(a.ELTransactionsRoot[:])

	// Field (1) 'ELWithdrawalsRoot'
	hh.PutBytes(a.ELWithdrawalsRoot[:])

	// Field (2) 'BuilderAddress'
	hh.PutBytes(a.BuilderAddress[:])

	// Field (3) 'BuilderProof'
	{
		subIndx := hh.Index()
		num := uint64(len(a.BuilderProof))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.BuilderProof {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	// Field (4) 'FeeRecipientAddress'
	hh.PutBytes(a.FeeRecipientAddress[:])

	// Field (5) 'FeeRecipientProof'
	{
		subIndx := hh.Index()
		num := uint64(len(a.FeeRecipientProof))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.FeeRecipientProof {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	// Field (6) 'FeePayerAddress'
	hh.PutBytes(a.FeePayerAddress[:])

	// Field (7) 'FeePayerProof'
	{
		subIndx := hh.Index()
		num := uint64(len(a.FeePayerProof))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.FeePayerProof {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	// Field (8) 'ELPlaceholderTxProof'
	{
		subIndx := hh.Index()
		num := uint64(len(a.ELPlaceholderTxProof))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.ELPlaceholderTxProof {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	// Field (9) 'CLPlaceholderTxProof'
	{
		if size := len(a.CLPlaceholderTxProof); size > 1073741824 {
			err = ssz.ErrListTooBigFn("AdjustmentDataV2.CLPlaceholderTxProof", size, 1073741824)
			return
		}
		subIndx := hh.Index()
		for _, i := range a.CLPlaceholderTxProof {
			hh.Append(i[:])
		}
		numItems := uint64(len(a.CLPlaceholderTxProof))
		hh.MerkleizeWithMixin(subIndx, numItems, 1073741824)
	}

	// Field (10) 'PlaceholderReceiptProof'
	{
		subIndx := hh.Index()
		num := uint64(len(a.PlaceholderReceiptProof))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.PlaceholderReceiptProof {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	// Field (11) 'PrePaymentLogsBloom'
	hh.PutBytes(a.PrePaymentLogsBloom[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AdjustmentDataV2 object
func (a *AdjustmentDataV2) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}
