// Code generated by fastssz. DO NOT EDIT.
// Hash: dbe7acddaff3f701b4779e6378eb483aebd048deb8708c3200d966c216d0b725
// Version: 0.1.3
package optimisticv3

import (
	v1 "github.com/attestantio/go-builder-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionV3 object to a target array
func (h *HeaderSubmissionV3) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionV3 object with a hasher
func (h *HeaderSubmissionV3) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionV3 object
func (h *HeaderSubmissionV3) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the VersionedSignedHeaderSubmission object to a target array
func (v *VersionedSignedHeaderSubmission) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the VersionedSignedHeaderSubmission object with a hasher
func (v *VersionedSignedHeaderSubmission) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the VersionedSignedHeaderSubmission object
func (v *VersionedSignedHeaderSubmission) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}

// MarshalSSZ ssz marshals the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedHeaderSubmissionDeneb object to a target array
func (s *SignedHeaderSubmissionDeneb) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedHeaderSubmissionDeneb object with a hasher
func (s *SignedHeaderSubmissionDeneb) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedHeaderSubmissionDeneb object
func (s *SignedHeaderSubmissionDeneb) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedHeaderSubmissionElectra object to a target array
func (s *SignedHeaderSubmissionElectra) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedHeaderSubmissionElectra object with a hasher
func (s *SignedHeaderSubmissionElectra) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedHeaderSubmissionElectra object
func (s *SignedHeaderSubmissionElectra) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the SignedHeaderSubmissionFulu object
func (s *SignedHeaderSubmissionFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedHeaderSubmissionFulu object to a target array
func (s *SignedHeaderSubmissionFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedHeaderSubmissionFulu object
func (s *SignedHeaderSubmissionFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[4:100])

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedHeaderSubmissionFulu object
func (s *SignedHeaderSubmissionFulu) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedHeaderSubmissionFulu object
func (s *SignedHeaderSubmissionFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedHeaderSubmissionFulu object with a hasher
func (s *SignedHeaderSubmissionFulu) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedHeaderSubmissionFulu object
func (s *SignedHeaderSubmissionFulu) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionDenebV2 object to a target array
func (h *HeaderSubmissionDenebV2) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionDenebV2 object with a hasher
func (h *HeaderSubmissionDenebV2) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionDenebV2 object
func (h *HeaderSubmissionDenebV2) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionElectra object to a target array
func (h *HeaderSubmissionElectra) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionElectra object with a hasher
func (h *HeaderSubmissionElectra) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionElectra object
func (h *HeaderSubmissionElectra) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the HeaderSubmissionFulu object
func (h *HeaderSubmissionFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(h)
}

// MarshalSSZTo ssz marshals the HeaderSubmissionFulu object to a target array
func (h *HeaderSubmissionFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(476)

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if dst, err = h.BidTrace.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'ExecutionPayloadHeader'
	dst = ssz.WriteOffset(dst, offset)
	if h.ExecutionPayloadHeader == nil {
		h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	offset += h.ExecutionPayloadHeader.SizeSSZ()

	// Offset (2) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	if h.ExecutionRequests == nil {
		h.ExecutionRequests = new(electra.ExecutionRequests)
	}
	offset += h.ExecutionRequests.SizeSSZ()

	// Offset (3) 'Commitments'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(h.Commitments) * 48

	// Offset (4) 'AdjustmentData'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'ExecutionPayloadHeader'
	if dst, err = h.ExecutionPayloadHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'ExecutionRequests'
	if dst, err = h.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'Commitments'
	if size := len(h.Commitments); size > 4096 {
		err = ssz.ErrListTooBigFn("HeaderSubmissionFulu.Commitments", size, 4096)
		return
	}
	for ii := 0; ii < len(h.Commitments); ii++ {
		dst = append(dst, h.Commitments[ii][:]...)
	}

	// Field (4) 'AdjustmentData'
	if dst, err = h.AdjustmentData.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the HeaderSubmissionFulu object
func (h *HeaderSubmissionFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 476 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2, o3, o4 uint64

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if err = h.BidTrace.UnmarshalSSZ(buf[0:460]); err != nil {
		return err
	}

	// Offset (1) 'ExecutionPayloadHeader'
	if o1 = ssz.ReadOffset(buf[460:464]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 476 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'ExecutionRequests'
	if o2 = ssz.ReadOffset(buf[464:468]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'Commitments'
	if o3 = ssz.ReadOffset(buf[468:472]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Offset (4) 'AdjustmentData'
	if o4 = ssz.ReadOffset(buf[472:476]); o4 > size || o3 > o4 {
		return ssz.ErrOffset
	}

	// Field (1) 'ExecutionPayloadHeader'
	{
		buf = tail[o1:o2]
		if h.ExecutionPayloadHeader == nil {
			h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
		}
		if err = h.ExecutionPayloadHeader.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'ExecutionRequests'
	{
		buf = tail[o2:o3]
		if h.ExecutionRequests == nil {
			h.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = h.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (3) 'Commitments'
	{
		buf = tail[o3:o4]
		num, err := ssz.DivideInt2(len(buf), 48, 4096)
		if err != nil {
			return err
		}
		h.Commitments = make([]deneb.KZGCommitment, num)
		for ii := 0; ii < num; ii++ {
			copy(h.Commitments[ii][:], buf[ii*48:(ii+1)*48])
		}
	}

	// Field (4) 'AdjustmentData'
	{
		buf = tail[o4:]
		if err = h.AdjustmentData.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the HeaderSubmissionFulu object
func (h *HeaderSubmissionFulu) SizeSSZ() (size int) {
	size = 476

	// Field (1) 'ExecutionPayloadHeader'
	if h.ExecutionPayloadHeader == nil {
		h.ExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	size += h.ExecutionPayloadHeader.SizeSSZ()

	// Field (2) 'ExecutionRequests'
	if h.ExecutionRequests == nil {
		h.ExecutionRequests = new(electra.ExecutionRequests)
	}
	size += h.ExecutionRequests.SizeSSZ()

	// Field (3) 'Commitments'
	size += len(h.Commitments) * 48

	// Field (4) 'AdjustmentData'
	size += h.AdjustmentData.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the HeaderSubmissionFulu object
func (h *HeaderSubmissionFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(h)
}

// HashTreeRootWith ssz hashes the HeaderSubmissionFulu object with a hasher
func (h *HeaderSubmissionFulu) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'BidTrace'
	if h.BidTrace == nil {
		h.BidTrace = new(v1.BidTrace)
	}
	if err = h.BidTrace.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'ExecutionPayloadHeader'
	if err = h.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'ExecutionRequests'
	if err = h.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'Commitments'
	{
		if size := len(h.Commitments); size > 4096 {
			err = ssz.ErrListTooBigFn("HeaderSubmissionFulu.Commitments", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range h.Commitments {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(h.Commitments))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	// Field (4) 'AdjustmentData'
	if err = h.AdjustmentData.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the HeaderSubmissionFulu object
func (h *HeaderSubmissionFulu) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(h)
}

// MarshalSSZ ssz marshals the GetPayloadV3 object
func (g *GetPayloadV3) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV3 object to a target array
func (g *GetPayloadV3) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV3 object
func (g *GetPayloadV3) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV3 object
func (g *GetPayloadV3) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the GetPayloadV3 object
func (g *GetPayloadV3) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV3 object with a hasher
func (g *GetPayloadV3) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the GetPayloadV3 object
func (g *GetPayloadV3) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(g)
}

// MarshalSSZ ssz marshals the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedGetPayloadV3 object to a target array
func (s *SignedGetPayloadV3) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) SizeSSZ() (size int) {
	size = 4
	return
}

// HashTreeRoot ssz hashes the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedGetPayloadV3 object with a hasher
func (s *SignedGetPayloadV3) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedGetPayloadV3 object
func (s *SignedGetPayloadV3) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
